### ISSUE TITLE
Allow for (List[np.ndarray], List[np.ndarray], List[str])  as an init arg for DomainAwareDataset

### ISSUE THREAD

**Issue by YanisLalou** [scikit-adaptation/skada#107]
Rn DomainAwareDataset accepts:
```
 def __init__(
        self,
        # xxx(okachaiev): not sure if dictionary is a good format :thinking:
        domains: Union[List[DomainDataType], Dict[str, DomainDataType], None] = None
    ):
```
with 
```
DomainDataType = Union[
    # (name, X, y)
    Tuple[str, np.ndarray, np.ndarray],
    # (X, y)
    Tuple[np.ndarray, np.ndarray],
    # (X,)
    Tuple[np.ndarray, ],
]
```

I feel like it would be easier to also be able to init a `DomainAwareDataset` like that:

```
sample_domain = [1, 1, 1, 2, 2]
X = [0, 1, 0, 1, 2]
y = [0, 1, 0, 0, 1]

dataset = DomainAwareDataset(X, y, sample_domain)
```

**Comment by kachayev** [comment]
Thé key purpose of the `DomainAwareDataset` is to make it easier to generate `sample_domain` based on what you decide to be source and what goes as target. Think about the situation where you have images from different datasets and their labels: the dataset does not prescribe the role for any of those, you do it only when calling 'pack'. Now, if you already got `sample_domain` somewhere you just don't need `DomainAwareDataset`, it is just an inappropriate abstraction all together. If we allow passing `sample_domain` we also need a way to translate domain labels to names so those names could be used for `pack`. And, again, seems like tackling the problem from a wrong side: you've already done this in your code somewhere or, otherwise, where `sample_domain` came from in the first place?

**Comment by YanisLalou** [comment]
Oh yeah my bad, I think I wasn't clear about what I am talking about. In my example, the `sample_domain` array is not the same kind as we use in skada, meaning that it doesn't use the negative/positive convention for target/source domains.
That's why I wanted to use the `DomainAwareDataset` object, to be able to use the `pack` functions. And thus to have the  negative/positive convention + to mask target labels.

**Basically I wanted to have a solution for this use-case:**
I have a dataset in a dataframe. I have n columns that I want to use as `X`, m columns for `y` and one categorical column that I want to use as the `sample_domain`. Thus here I have my `X`, `y` and `sample_domain` arrays but they don't follow skada conventions.
Thus I want a solution to select which domains will be the target domains and to mask the corresponding `y` labels. That's why I thought that the `DomainAwareDataset` object could do all that with that kind of inputs.
